### PR TITLE
Revert "Require rspec instead of only expectations to fix load issue …

### LINKED ISSUE #425: Undefined method 'enumerize' for RSpec::ExampleGroups in Rails 7.0.4.3
After upgrading to `Rails 7.0.4.3 / Rack 2.2.6.4` enumerize is no longer included in Rspecs.

Example.
```
it { is_expected.to enumerize(:field).in(array_of_items) }
```
Fails with `Undefined method 'enumerize' for #<RSpec::ExampleGroups...`.

Current solution:

Add to `rails_helper.rb`: `require "enumerize/integrations/rspec"`

### PR DESCRIPTION
**Pull request by softwaregravy**
This reverts commit 28dd2247ec03ef9a7e74266060d443ed8df1c2b4.

This fixes #425 for my specific test that was failing when upgrading to 2.6.1

I don't know what the load issue this was intended to fix, so this might cause problems for others.

### CODE REVIEW

**Comment by nashby** [comment]
@softwaregravy yeah, it supposed to fix some issue with spring but think having it's broken this way is worse. Thanks!
