### ISSUE TITLE
rails 4.2.5 and enumerize 1.1.0 class inheritance issue

### ISSUE THREAD

**Issue by elarcent** [brainspec/enumerize#224]
Hi,

We ran into issue with enumerize after we upgraded to Rails 4.2.5 from 4.2.0 (and also to ruby 2.3.0)
Inherited classes that have enumerize defined in their superclasses raise the following error when we try to access enumerized attribute:

```
NoMethodError: undefined method `find_value' for nil:NilClass
	from /home/path/bundle/ruby/2.3.0/gems/enumerize-1.1.0/lib/enumerize/attribute.rb:86:in `pay_system'
	from (irb):3
	from /home/path/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
	from /home/path/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /home/path/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/path/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/path/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

The issue happens only in production mode. In Dev mode working properly.

**Comment by nashby** [comment]
@elarcent hey!  Can you please provide a sample application that reproduces the error?

**Comment by nashby** [comment]
Closing this for now since I run 4.2.5 rails app with enumerize in production and don't have this issue. Feel free to ping me when you have a way how to reproduce it. Thanks!
